# Generated by Django 5.1.4 on 2024-12-13 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AircraftType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(max_length=255, verbose_name="Aircraft Type"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("FLYING", "Flying"),
                            ("MAINTENANCE", "Maintenance"),
                        ],
                        default="AVAILABLE",
                        max_length=255,
                        verbose_name="Aircraft Status",
                    ),
                ),
                (
                    "aircraft_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat.aircrafttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Engineer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Engineer Name"),
                ),
                (
                    "aircraft_types",
                    models.ManyToManyField(
                        blank=True,
                        related_name="aircraft_types",
                        to="chat.aircrafttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="Work Date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WORKING", "Working"),
                            ("VACATION", "Vacation"),
                            ("SICK_LEAVE", "Sick Leave"),
                        ],
                        default="WORKING",
                        max_length=255,
                        verbose_name="Work Status",
                    ),
                ),
                ("mh", models.IntegerField(max_length=255, verbose_name="MH")),
                (
                    "aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="chat.aircraft"
                    ),
                ),
                (
                    "engineer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="chat.engineer"
                    ),
                ),
            ],
            options={
                "unique_together": {("engineer", "aircraft", "date")},
            },
        ),
    ]
