# Generated by Django 5.1.4 on 2024-12-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_aircraft_aircraft_sn_alter_work_mh"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="date",
            field=models.DateField(verbose_name="Work Date"),
        ),
    ]
