# Generated by Django 5.1.4 on 2024-12-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_work_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="engineer",
            name="surname",
            field=models.CharField(
                default="Alex", max_length=255, verbose_name="Engineer Surname"
            ),
            preserve_default=False,
        ),
    ]
